#!/bin/bash

server=$1

rm -f "$HOME/coreos-k8s-cluster/control/kubeconfig"
kubectl --kubeconfig="$HOME/coreos-k8s-cluster/control/kubeconfig" config set-cluster k8cluster-01 --server=http://$server:8080
kubectl --kubeconfig="$HOME/coreos-k8s-cluster/control/kubeconfig" config set-context default-context --cluster=k8cluster-01
kubectl --kubeconfig="$HOME/coreos-k8s-cluster/control/kubeconfig" config use-context default-context
